# Generated by Django 6.0.4 on 2026-05-03 09:48

import core.models
import django.db.models.deletion
from django.db import migrations, models


def create_default_branch(apps, schema_editor):
    Branch = apps.get_model('core', 'Branch')
    Branch.objects.get_or_create(name='Main Branch')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_allow_item_deletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_branch, migrations.RunPython.noop),
        migrations.AddField(
            model_name='item',
            name='branch',
            field=models.ForeignKey(default=core.models.get_default_branch, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.branch'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(default=core.models.get_default_branch, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.branch'),
        ),
    ]
